
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'service-jk'
    backendAzureRmResourceGroupName: 'jksoam'
    backendAzureRmStorageAccountName: 'jksoam123456'
    backendAzureRmContainerName: 'jksoam'
    backendAzureRmKey: 'terraform.tfstate'
